### ISSUE TITLE
Problema con el podspec

### ISSUE THREAD

**Issue by narbonaMeep** [Masabi/Podspecs#34]
Buenos días.

nos hemos encontrado en iOS un problema con el podspec de JustRide
https://github.com/Masabi/Podspecs
![image](https://github.com/user-attachments/assets/00eb9ed5-84f7-4288-a79e-81ee2ca34a53)
![image](https://github.com/user-attachments/assets/afbae5f4-9b06-4bf9-a41d-9415f5c1da9f)

Me comenta el equipo que parece ser del siguiente commit
https://github.com/Masabi/Podspecs/commit/958f94f694d4b0e70b7d9c2ab664ce4df2ddc0b4

Tampoco hemos visto nada en la documentación con respecto a esto.
![image](https://github.com/user-attachments/assets/a3f53984-0565-40d4-b919-d07596a51594)

Por favor dadle prioridad porque nos rompe todo el flujo de build.

**Comment by adil-hussain-84** [comment]
@narbonaMeep: Thanks for reporting 🙏 We are working on a fix.
